
import { GoogleGenAI } from "@google/genai";

/**
 * Generates a meme using Gemini based on a prompt and optional reference image.
 */
export const generateMeme = async (
  prompt: string,
  base64Image?: string,
  mimeType?: string
): Promise<string> => {
  try {
    const apiKey = process.env.API_KEY || '';
    if (!apiKey) throw new Error("API Key is missing.");

    const ai = new GoogleGenAI({ apiKey });

    // Updated system prompt to strictly enforce the specific character appearance
    // defined by the reference image provided by the user.
    const systemPrompt = `Create a STUNNING, MASTERPIECE QUALITY 3D voxel art render (Minecraft style with RTX shaders).

    VISUAL STYLE GUIDE:
    - **Render Engine Look**: Unreal Engine 5, Octane Render, or Blender Cycles with high-end cinematic settings.
    - **Lighting**: Warm, golden, magical atmosphere. Use volumetric lighting, bloom, and floating golden dust particles/sparkles/bokeh.
    - **Textures**: High-definition voxel textures. Materials should look tangible (smooth plastic/ceramic for the piggy, realistic wood/stone/metal for environment).
    - **Camera**: Use significant depth of field (bokeh) to blur the background and focus sharply on the character.

    STRICT CHARACTER DEFINITION (THE "FLYWHEEL PIGGY BANK"):
    You must ALWAYS render the EXACT SAME character in every image.
    - **Base Model**: A classic Minecraft Pig (cubic body, head, short legs, protruding snout).
    - **Color**: Vibrant Pig Pink (#F08080) with subtle texture details.
    - **MANDATORY FEATURE 1 (WINGS)**: The pig MUST have two cute, white, voxelated ANGEL WINGS on its back.
    - **MANDATORY FEATURE 2 (SLOT)**: A golden coin slot on top of its head (if the top is visible).
    - **Eyes**: Standard wide-set black pixel eyes (cute expression).
    - **Snout**: Protruding rectangular pink snout.
    - **Accessories**: Do not add clothes unless the prompt specifically asks for a costume. The base character is just the winged pig.

    SCENE CONTEXT:
    ${prompt}

    CRITICAL INSTRUCTION: 
    - **CONSISTENCY**: The character must look like the "Flywheel Piggy Bank" described above. Do not change it into a generic pig or a human. It is a blocky, winged piggy bank.
    - **NO TEXT**: Do NOT include any text, captions, watermark, or UI elements.
    - **QUALITY**: Make it look like a premium video game promotional art. Vibrant, saturated, and magical.

    If the user's prompt implies a specific action (e.g., "cooking", "driving"), adapt the character's pose and surroundings, but KEEP THE CHARACTER DESIGN (Pink + Wings) intact.`;

    const parts: any[] = [{ text: systemPrompt }];

    // If user uploaded a reference image, include it
    if (base64Image && mimeType) {
      const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
      parts.push({
        inlineData: {
          data: cleanBase64,
          mimeType: mimeType,
        },
      });
      parts[0].text += " Use the attached image as a composition/pose reference, but IGNORE the character in the image and REPLACE it with the Flywheel Piggy Bank (Pink Voxel Pig with Wings) described above.";
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts },
    });

    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error('No image generated by the AI.');
  } catch (error: any) {
    console.error('Meme Generation Error:', error);
    throw error;
  }
};
