
import { GoogleGenAI } from "@google/genai";

/**
 * Generates a meme using Gemini based on a prompt and optional reference image.
 */
export const generateMeme = async (
  prompt: string,
  base64Image?: string,
  mimeType?: string
): Promise<string> => {
  try {
    const apiKey = process.env.API_KEY || '';
    if (!apiKey) throw new Error("API Key is missing.");

    const ai = new GoogleGenAI({ apiKey });

    // Updated system prompt to match the high-quality "Chef Piggy" reference style:
    // Cinematic, warm lighting, particles, depth of field, RTX/Unreal Engine 5 look.
    const systemPrompt = `Create a STUNNING, MASTERPIECE QUALITY 3D voxel art render (Minecraft style with RTX shaders).

    VISUAL STYLE GUIDE:
    - **Render Engine Look**: Unreal Engine 5, Octane Render, or Blender Cycles with high-end cinematic settings.
    - **Lighting**: Warm, golden, magical atmosphere. Use volumetric lighting, bloom, and floating golden dust particles/sparkles/bokeh.
    - **Textures**: High-definition voxel textures. Materials should look tangible (smooth plastic/ceramic for the piggy, realistic wood/stone/metal for environment).
    - **Camera**: Use significant depth of field (bokeh) to blur the background and focus sharply on the character.
    - **Detail Level**: Extremely high. Adds small details like glowing particles, coin glints, and rich environmental textures.

    MAIN CHARACTER:
    - A cute, blocky PINK MINECRAFT PIGGY BANK.
    - IMPORTANT: It has TWO SMALL WHITE WINGS on its back.
    - It looks heroic, cute, or busy depending on the context.

    SCENE CONTEXT:
    ${prompt}

    CRITICAL INSTRUCTION: 
    - NO TEXT. Do NOT include any text, captions, watermark, or UI elements.
    - If the user asks for text, only then include it as 3D block text in the scene, otherwise keep it clean.

    Make it look like a premium video game promotional art. Vibrant, saturated, and magical.`;

    const parts: any[] = [{ text: systemPrompt }];

    // If user uploaded a reference image, include it
    if (base64Image && mimeType) {
      const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
      parts.push({
        inlineData: {
          data: cleanBase64,
          mimeType: mimeType,
        },
      });
      parts[0].text += " Use the attached image as a composition reference, but strictly apply the 3D Voxel/Minecraft visual style described above.";
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts },
    });

    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error('No image generated by the AI.');
  } catch (error: any) {
    console.error('Meme Generation Error:', error);
    throw error;
  }
};
