
import { GoogleGenAI } from "@google/genai";

/**
 * Generates a meme using Gemini based on a prompt and optional reference image.
 */
export const generateMeme = async (
  prompt: string,
  base64Image?: string,
  mimeType?: string
): Promise<string> => {
  try {
    const apiKey = process.env.API_KEY || '';
    if (!apiKey) throw new Error("API Key is missing.");

    const ai = new GoogleGenAI({ apiKey });

    // Cheerful system prompt focusing on bright, funny Minecraft voxel art
    const systemPrompt = `Create a high-quality 3D Minecraft-style voxel art meme. 
    STYLE: Strictly blocky, pixelated, but with EXTREMELY bright, cheerful, 'Overworld' sunlight lighting. Vibrant saturated colors.
    MAIN CHARACTER: A cute, blocky, pink voxel piggy bank with a golden coin slot AND TWO WHITE WINGS on its back. The winged piggy should look happy, funny, and heroic.
    THEME: Flywheel Piggy Bank ($BANK) on Solana.
    CONTEXT: ${prompt}. 
    Make it look like a high-end 3D render from a modern Minecraft cinematic (like Raytracing/RTX style). 
    Avoid dark, gloomy, or gray tones. Everything should be sunny and fun.
    If there's a reference image, turn the scene/person in that image into a Minecraft voxel version of themselves alongside the winged piggy.`;

    const parts: any[] = [{ text: systemPrompt }];

    // If user uploaded a reference image, include it
    if (base64Image && mimeType) {
      const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
      parts.push({
        inlineData: {
          data: cleanBase64,
          mimeType: mimeType,
        },
      });
      parts[0].text += " Use the attached image as a direct reference to 'Minecraft-ify' the scene.";
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts },
    });

    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error('No image generated by the AI.');
  } catch (error: any) {
    console.error('Meme Generation Error:', error);
    throw error;
  }
};
